### ISSUE TITLE
wishlist profile block does not render on the profile page

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/customer-account-tutorials#57]
Using the code within the example and based on https://shopify.dev/changelog/customer-account-full-page-extensions-can-now-be-declared-linkable I added   `allow_direct_linking = true` to extensions/wishlist-profile-block/shopify.extension.toml but still do not see the the content load from `ProfileBlockExtension.tsx`

> @shopify/cli/3.66.0 darwin-x64 node-v22.6.0

**Comment by kirakik** [comment]
Hey @Jay-Plumb 👋 this should now be fixed. We hadn't rolled out the feature fully when we released that changelog post, it was meant for developers to prepare for the feature to be released.
